--liquibase formatted sql
--changeset vemedvedev:USERS
CREATE TABLE SCHED.MESSAGES (
	ID BIGINT generated always as identity,
	MESSAGE VARCHAR(255),
	CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX MESSAGE_ID_INDX ON SCHED.MESSAGES (ID);
